### ISSUE TITLE
Admin screen not accessible in Magento 1.9.2.2

### ISSUE THREAD

**Issue by janzikmund** [quafzi/magento-exportFullImagePath#1]
Just installed this logged in and out from admin, and cleaned cache a few times, but when accessing the settings screen under System > Configuration > Settings > CSV, I keep getting a 404 error. So there is no way to turn the module on.

**Comment by janzikmund** [comment]
just sent you a pull request fixing this ;)

**Comment by quafzi** [comment]
Thank you!
